### ISSUE TITLE
[BUG] Unable to reinitialize plugin after getting GDPR consent

### ISSUE THREAD

**Issue by bouncymarble** [Poing-Studios/godot-admob-ios#17]
Hi, first of all, thanks for the plugin, I've been using it in my iOS app that was released recently, and now I'd like to implement GDPR consent, I just realized that your plugin also supports this. I'm almost done debugging it, but I noticed that the plugin won't reinitialize after getting user consent (in case they choose non-personalized ads), I couldn't find "is_personalized" parameter or something like that in your initialization function (https://github.com/Poing-Studios/godot-admob-ios/blob/master/plugin/admob/src/main/admob.mm#L143), so I'm curious how do you forward consent to the Google Mobile Ads SDK?

I'm using https://github.com/Shin-NiL/Godot-Android-Admob-Plugin + https://github.com/pschw/GodotConsentPlugin for the Android version of my app and I'm able to reinitialize the admob plugin with the "is_personalized" parameter set to false when users don't consent, Shin-NiL's plugin also configures GADRequest (https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/blob/main/admob-plugin/godotadmob/src/main/java/shinnil/godot/plugin/android/godotadmob/GodotAdMob.java#L115) as described in the admob documentation (https://developers.google.com/admob/ump/android/quick-start#forward-consent / https://developers.google.com/admob/ump/ios/quick-start#forward-consent). I just want to make sure your plugin works the same to comply with GDPR, since I'm thinking of using it in android too instead of Shin-NiL's.

Btw, the consent works as expected with "Test Europe User Consent" enabled or using a vpn, but when testing it in my location (Colombia), it still shows a window but only with a continue button and a different text that says something like "ads keep our app free, select allow in the next screen...", then it shows ATT consent as expected (I use another plugin for that), is that intended? because the console prints "Consent Form Available" and then "User consent obtained. Personalization not defined." when I was actually expecting "Consent Form not Available" or "User consent not required. For example, the user is not in the EEA or the UK.".

Hope I made myself understood, and please let me know if these are bugs or missing features, I'd like to contribute but idk much about those languages nor creating plugins, anyways, thanks for reading.

Plugin v2.0.4
Editor plugin v1.2.4
Godot v3.4.2

**Comment by gumaciel** [comment]
Hello, thank you for using our plugin!

> I couldn't find "is_personalized" parameter or something like that in your initialization function

We don't use `is_personalized` parameter because when I developed this part of GDPR, in the documentation of AdMob I remember it said that it was deprecated to do it this way, so we only use UMP and to talk about whether it is personalized or not, you need to change it within the AdMob application: http://admob.google.com/

> I just want to make sure your plugin works the same to comply with GDPR

Yes it does, but i have not done much tests because i don't live in Europe.

From what I analyzed in the codes, I don't know how "GodotConsentPlugin" will communicate with "Godot-Android-Admob-Plugin" can you tell me how you are using these two Plugins?

For example, if in AdMob you defined by code to always be `isPersonalized = true`, from what I understand, regardless of what the user selects, it will always be personalized, I believe that what the "Forward consent" is used for the game to always demonstrate personalized ads or not

I saw that in the code it is considering these 3 consent statuses:

```gdscript
enum CONSENT_STATUS {
    UNKNOWN,
    NON_PERSONALIZED,
    PERSONALIZED
}
```
But I remember that when I tested as i was developing, regardless of whether the user clicked "Consent" or "Do not consent", AdMob can't know what he clicked, so for me there's no way to know if it was granted or not, but I'll do some tests to guarantee

Check the documentation: https://developers.google.com/admob/ump/android/quick-start#present_the_form_if_required

There are only four Status: https://developers.google.com/admob/ump/android/api/reference/com/google/android/ump/ConsentInformation.ConsentStatus
- `ConsentStatus.UNKNOWN`: Unknown consent status.
- `ConsentStatus.REQUIRED`: User consent required but not yet obtained.
- `ConsentStatus.NOT_REQUIRED`: User consent not required. For example, the user is not in the EEA or the UK.
- `ConsentStatus.OBTAINED`: User consent obtained. Personalization not defined.

> but when testing it in my location (Colombia), it still shows a window but only with a continue button and a different text that says something like "ads keep our app free, select allow in the next screen..."

It should not happen, maybe you forgot to export again? I will test it, by the way i also live on South America.

> then it shows ATT consent as expected (I use another plugin for that), is that intended?

I don't think so

> because the console prints "Consent Form Available" and then "User consent obtained. Personalization not defined."

Oh, maybe as you have accepted before "being" in europe, what you selected was saved, for that you would need to reset the consent using this method: https://github.com/Poing-Studios/godot-admob-ios/blob/master/plugin/admob/src/main/admob.mm#L97


Also: I've done some research now and it doesn't seem to be deprecated to declare "npa=1", they added it to the updated "EU Consent" page maybe it's a good idea to add the "isPersonalized" parameter but I really don't know if it's recommended since AdMob says this on end of page: https://developers.google.com/admob/ump/ios/quick-start#forward-consent

`If non-personalized ads are requested, the ad request URL currently includes &npa=1. However, note that this is an internal implementation detail of the Google Mobile Ads SDK and is subject to change.`

**Comment by gumaciel** [comment]
If you want to help me contribute to this part of the GDPR, you can join the Discord link: https://github.com/Poing-Studios/godot-admob-android/discussions/63

This is something I really need help with as the AdMob documentation isn't very good and as I don't live in Europe it just makes it more difficult

**Comment by gumaciel** [comment]
Also: Our Android and iOS Plugin code should be identical, so GDPR should work the same for Android and iOS

I don't recommend using multiple Plugins for the "same" purpose because in addition to being bad to maintain the plugins, you will probably have to rewrite code for each operating system, Android and iOS

**Comment by gumaciel** [comment]
Maybe this old issue can help you in any way: https://github.com/Poing-Studios/godot-admob-android/issues/57

**Comment by bouncymarble** [comment]
> can you tell me how you are using these two Plugins?

So this is how I use "GodotConsentPlugin" and reinitialize "Godot-Android-Admob-Plugin": https://github.com/bouncymarble/bouncymarble.github.io/blob/main/ConsentPlugin.gd

Btw, I had to add a neutral age screen that asks the user for their age before asking for GDPR consent (Google Play rejected my app the first time because consent shouldn't be shown to children under 13).

> I saw that in the code it is considering these 3 consent statuses

Yeah I was wondering why the statuses are different, also the form interface is very different as you can see in the demo video (https://youtu.be/PJ2H8ZK8O_w), but I just realized they actually use "Personalized Ad Consent SDK" which is now deprecated (https://developers.google.com/admob/android/eu-consent/) instead of UMP SDK, so I think I must migrate to your plugin.

> so we only use UMP and to talk about whether it is personalized or not, you need to change it within the AdMob application: http://admob.google.com/

Ok, should I set it to non-personalized or keep it personalized (default)?

> Oh, maybe as you have accepted before "being" in europe, what you selected was saved

Hmm you might be right, maybe I forgot to reset it. I just need to make sure the user is not in europe (with the signal "consent_info_update_success" or "consent_status_changed") so I don't show them a "data usage" button from my game settings to update their consent.

> you can join the Discord link

Thanks for the link.

> I don't recommend using multiple Plugins for the "same" purpose because in addition to being bad to maintain the plugins, you will probably have to rewrite code for each operating system, Android and iOS

Yeah I've been trying to merge my Android and iOS projects with your plugin so it's easier for me to release updates.

> Maybe this old issue can help you in any way: [Poing-Studios/godot-admob-android#57](https://github.com/Poing-Studios/godot-admob-android/issues/57)

Well, I've had no issues updating the consent for european users, just added a "data usage" button in my game settings panel with this code:

`func _on_TB_UpdateGDPR_button_up():
	MobileAds.reset_consent_state()
	MobileAds.request_user_consent()`

Although it still shows the button for non european users, but maybe it's due to the above mentioned, so I need to test it again. Thank you so much for your help.

**Comment by gumaciel** [comment]
> So this is how I use "GodotConsentPlugin" and reinitialize "Godot-Android-Admob-Plugin": https://github.com/bouncymarble/bouncymarble.github.io/blob/main/ConsentPlugin.gd

I think this will not work, i just tested here on my phone and the buttons "Consent" and "Do not Consent" have the same result: Get the `ConsentStatus.OBTAINED` which means this: https://developers.google.com/admob/ump/android/api/reference/com/google/android/ump/ConsentInformation.ConsentStatus#public-static-final-int-obtained.

> I had to add a neutral age screen that asks the user for their age before asking for GDPR consent (Google Play rejected my app the first time because consent shouldn't be shown to children under 13).

I didn't know that, maybe we can include this in the plugin or create a new plugin to display this part of getting the user's age and thus displaying the form or not

> also the form interface is very different as you can see in the demo video (https://youtu.be/PJ2H8ZK8O_w)

Yes, i think this is a deprecated version

> Ok, should I set it to non-personalized or keep it personalized (default)?

Unfortunately I don't know the answer to this question :(

But where you can configure this is here:
![image](https://user-images.githubusercontent.com/20030153/152661371-f09cc91e-9c55-456a-bbb0-497f36e30949.png)
![image](https://user-images.githubusercontent.com/20030153/152661359-6a5651fb-9bf8-436c-bdd4-05f0f691df1e.png)


> Although it still shows the button for non european users
Remember to unmark this button:

![image](https://user-images.githubusercontent.com/20030153/152661442-25a2d7aa-4268-4565-9d03-1eabb9b3fc17.png)

If you mark this, whenever the user is or not on EEA, it will show the Form

**Comment by bouncymarble** [comment]
Closing this as there's no need to reinitialize the plugin, it seems the UMP handles user choice and somehow forwards it to the Google Mobile Ads SDK. Although there's this issue when "don't consent" button is pressed (or "manage options" and then "confirm choices" without selecting any consent option), ads won't load due to error code 3 (ERROR_CODE_NO_FILL), but this has nothing to do with the plugin, so the only way to load ads is by resetting and updating consent. More info about what admob requires to load either personalized or non-personalized ads: https://support.google.com/admob/answer/9760862?hl=en&ref_topic=9756841

Also, here are the answers to some questions about UMP and GDPR that @gumaciel and I asked on the Google Mobile Ads SDK Technical Forum: https://groups.google.com/g/google-admob-ads-sdk/c/xfLEdy06pyc

> the console prints "Consent Form Available" and then "User consent obtained. Personalization not defined." when I was actually expecting "Consent Form not Available" or "User consent not required. For example, the user is not in the EEA or the UK."

Regarding this issue, it turns out I didn't forget to unmark "Test Europe User Consent", and what is actually triggering this message "Consent Form Available" is the IDFA form that is required on iOS, no matter location. On Android it returns "Consent Form not Available" as expected if not in the EEA.

Btw, I had another issue when trying to start my app with no internet connection, the plugin tries to initialize and returns status 0 which I thought was ok, but @gumaciel tested it too and always gets status 1 (MobileAds.AdMobSettings.INITIALIZATION_STATUS.READY). The thing is when I turn on internet, initialize() keeps returning status 0, it seems like it can only be called once. Anyways, what I had to do is make sure there's internet connection to initialize the plugin. For this I use Timer and HTTPRequest nodes, here's the code in case anyone finds it useful:

```
func _on_Timer_CheckInternet_timeout():
	check_internet()


func check_internet():
	if http_request.get_http_client_status() != 0:
		return
	http_request.request("https://google.com")


func _on_HTTPRequest_request_completed(result, response_code, _headers, _body):
	if result == 0 and response_code == 200:
		if not MobileAds.get_is_initialized():
			MobileAds.ready_to_initialize()
```
