### ISSUE TITLE
[BUG] Incorrect load state signal in Reward Ads

### ISSUE THREAD

**Issue by kyoz** [Poing-Studios/godot-admob-ios#4]
**Describe the bug**

I think [this line](https://github.com/Poing-Studios/godot-admob-ios/blob/master/plugin/admob/src/formats/Rewarded.mm#L43) have incorrect signal, it should be load_fail rather than show_fail.

Just testing it on my iphone and this cause the Toast to repeating show just like when user click on view ads but there is no ads :D

**Expected behavior**

Should have valid signal

**Comment by gumaciel** [comment]
@kyoz Thank you for reporting it, i will fix it on the next update

**Comment by kyoz** [comment]
Hi @gumaciel , i finally found out. The plugin work perfectly, that's just the `ADAPTIVE` option. I'v used it in android so i think it will work on iOS too and keep it. But don't know why it doesn't work. I'v changed it to `SMART_BANNER` and now it working normally on both Simulator and Real Devices. :D

**Comment by kyoz** [comment]
In XCode i can see it is loaded but don't know why it doesn't show so i don't know it's problem in iOS or on plugin side.

**Comment by kyoz** [comment]
Hi @gumaciel , I've just build and test it, doesn't know if my build progress is correct but i'v got this error in XCode output @@

```
**ERROR**: In Object of type 'Node': Attempt to connect nonexistent signal 'rewarded_ad_opened' to method 'CanvasLayer._on_rewarded_ad_opened'.
**ERROR**: In Object of type 'Node': Attempt to connect nonexistent signal 'rewarded_ad_opened' to method 'CanvasLayer._on_rewarded_ad_opened'.
e': Attempt to connect nonexistent signal 'rewarded_ad_closed' to method 'CanvasLayer._on_rewarded_ad_closed'.
**ERROR**: In Object of type 'Node': Attempt to connect nonexistent signal 'rewarded_ad_closed' to method 'CanvasLayer._on_rewarded_ad_closed'.
```

**Comment by kyoz** [comment]
Oh i know it, `MobileAds.plugin.connect("signal", self, "func") for now.

After testing i can see the `show_fail` and `load_fail` signal is now correct but after user watched, the `user_earned_rewarded` is not fired :cry:.

Also for the banner, the adaptive banner still doesn't show, other banner is all fine. Doesn't know why, but i think i'll use "SMART_BANNER" for ios for now.

**Comment by gumaciel** [comment]
@kyoz please try to use with the `Example.tscn`: https://github.com/Poing-Studios/godot-admob-editor/blob/f97e553f19dec7cebfa7ff7e4d42f8921eb3c899/addons/admob/develop/Example.tscn

If not works, try to delete the `.ipa` and export again.

**Comment by kyoz** [comment]
Thanks @gumaciel, yes i'v tried which develop folder in `godot-admob-editor`. Doesn't know why it not fire `user_earned_rewarded`. Maybe i've builded it wrong. I'll try it again. 😸

**Comment by gumaciel** [comment]
@kyoz you can test with this `.zip`
[admob-ios-dev-2_0_0.zip](https://github.com/Poing-Studios/godot-admob-ios/files/7102914/admob-ios-dev-2_0_0.zip)


Also: I just send a new update to Editor Plugin: https://github.com/Poing-Studios/godot-admob-editor/commit/007b79afdd0c67ad67d076bb8824978adec53b22 of this Issue: https://github.com/Poing-Studios/godot-admob-editor/issues/10

- Remove the need of "`Export -> Resources -> Filters to export non-resources...`, you need to put this: `res://addons/admob/*.json`"
- Changed the `.json` to a `.gd` Script which extends Node and only have a Dictionary Variable to store the config variable, located at: `addons/admob/config/Settings.gd`
- Removed `addons/admob/config/settings.json` due is useless now with the `Settings,gd`

Note: If change the Variables directly from the Editor and change the screen, then will give this error: ` Another resource is loaded from path 'res://addons/admob/config/Settings.gd' (possible cyclic resource inclusion).
`  because the Script is not fully reloaded when is saved, this won't change the functionality of the Plugin so it will only need to fix this for next versions.


So now you don't need to put anything here to export
![Captura de Tela 2021-09-02 às 23 32 11](https://user-images.githubusercontent.com/20030153/131941755-a6d96448-f880-4203-b1ac-09088ba6bfd2.png)

**Comment by gumaciel** [comment]
@kyoz Just tested here on the new version of Editor Plugin and iOS Plugin (that i send to you in few minutes ago) and it's working well the `user_earned_rewarded`:

![Captura de Tela 2021-09-02 às 23 44 25](https://user-images.githubusercontent.com/20030153/131942789-3c8c0044-77fb-433b-b69b-d339a61e7cce.png)

"EARNED coins with amount: 10"

**Comment by kyoz** [comment]
Hi @gumaciel , yeah just as you said, i'v delete the ipa project and export again and now everything work, both on example develop project and my project. Everything now is work perfectly. The option to auto toggle real ads on production is just awesome.

**Comment by gumaciel** [comment]
Nice, since everything seems to be fixed i will close the Issue, the issue of `ADAPTIVE BANNER` is here: https://github.com/Poing-Studios/godot-admob-ios/issues/6.
