### ISSUE TITLE
[FEATURE] About NSUserTrackingUsageDescription

### ISSUE THREAD

**Issue by kyoz** [Poing-Studios/godot-admob-ios#9]
Is this Privacy is required if i just use Admob. It's seem it only need if i'm using personalized ad. But there isn't an option to turn in off. @@

**Comment by gumaciel** [comment]
Currently it's mandatory only for iOS 14+:

https://developers.google.com/admob/ios/ios14#objective-c

https://github.com/Poing-Studios/godot-admob-ios/blob/master/plugin/admob/src/main/admob.mm#L182-L186

But we can on future make this optional.

**Comment by gumaciel** [comment]
![Captura de Tela 2021-09-04 às 15 34 06](https://user-images.githubusercontent.com/20030153/132104709-1e342e87-8f78-4050-90aa-43cadb3a1321.png)


I'm reading this now, so probably you will only need to put `NSUserTrackingUsageDescription` if you configured on the `Privacy & messaging`: https://support.google.com/admob/answer/10107561?hl=en

![Captura de Tela 2021-09-04 às 15 35 36](https://user-images.githubusercontent.com/20030153/132104756-2eec1f21-dd2c-462c-97eb-c8a71c7a884d.png)

**Comment by gumaciel** [comment]
Unfortunelly I can't develop on this because they are still migrating my account to the new `Privacy & messaging`: https://support.google.com/fundingchoices/answer/10647487, 

But you try to develop, it's not hard at all and I can help you on the Discord: https://discord.gg/FAMNVzBJ

**Comment by kyoz** [comment]
Hmm, i'v read it, just as you say, it's now mandatory for iOS 14+. I'll learn more about this.

**Comment by gumaciel** [comment]
@kyoz i invite you to test the new version of the Plugin, i just released the version:

Editor Plugin: v1.0.0
iOS Plugin: v2.0.0
Android Plugin: v2.0.0

Editor: https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.0.0
Android: https://github.com/Poing-Studios/godot-admob-android/releases/tag/v2.0.0
iOS: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.0.0


Soon i will try to work on this issue of "NSUserTrackingUsageDescription"

**Comment by kyoz** [comment]
Thanks @gumaciel , that's cool. I'll test it when i get home :D

**Comment by shafnaz** [comment]
Hi guys, 
I also seem to be having some issue with apptracking. I'm trying to publish my game with admob on app store:
Any solutions to this?
![image](https://user-images.githubusercontent.com/37254287/136667850-352fa8af-fddb-4ba4-819b-6428109b8b90.png)

**Comment by gumaciel** [comment]
@shafnaz thank you for telling this, i will work on this right now, seems if the app is for Kids, the app can't use the `App Tracking Transparency framework`.

The idea right now is stop using the `App Tracking Transparency framework` and use the UMP https://support.google.com/fundingchoices/answer/9995402, but won't work until a new update comes for the Plugin

**Comment by gumaciel** [comment]
@shafnaz Please test with these `.bin` (you can use the same `googlemobileadssdkios.zip`)

[admob.zip](https://github.com/Poing-Studios/godot-admob-ios/files/7316577/admob.zip)

**Comment by gumaciel** [comment]
Just released a new version with this changes: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.0.1

---

We also updated the Editor Plugin BUT IT'S **NOT** MANDATORY do the Editor Plugin update, if you update the Editor Plugin be aware because it can break your app: https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.1.0

**Comment by kyoz** [comment]
Thank you very much @gumaciel , i just tested is and it seem everything work perfectly. 

For it to work, i have to turn off 'Test Europe User Content' and 'Child Directed Treatment' then re-export. 

My app is not for kid so i think it's ok, but for app making for kids i think there is no other way to avoid this, we have to add NSUserTrackingUsageDescription and turn on 'Test Europe User Content' & 'Child Directed Treatment'. 

Cause Apple with test it and will may reject the app if it is for kids and doesn't have these options.

**Comment by gumaciel** [comment]
Hi @kyoz , The `Test Europe User Content` need to be disabled when you are exporting to the Store, because is only for the developers test when they are not on EEA.

It's ok to not show the App Tracking Transparency when `Child Directed Treatment` is off, read the message of Apple that send to @shafnaz : ```"Since Kids Category apps are noy allowed to collect, transmit or share identifiable information with third-parties, you should not implement App Tracking Transparency in your app."```

**Comment by kyoz** [comment]
Hi @gumaciel , thank you very much, it's seem now everything is cleared. I'v tested the plugin and it work perfectly.

**Comment by kyoz** [comment]
@shafnaz how about you, did new release help solved your problem, if so this issue can close for now

**Comment by shafnaz** [comment]
My goodness I'm busy trying to get my app launched for a month now. this is the message i got from apple today:
![image](https://user-images.githubusercontent.com/37254287/140171486-ee2e09dd-59d4-46bf-b267-c374f1f3eb04.png)

Any solutions?

**Comment by gumaciel** [comment]
@shafnaz Verify if `is_for_child_directed_treatment` is `true` and `max_ad_content_rating` is `G` also give a look on these links:

https://support.google.com/googleplay/android-developer/answer/9898834#zippy=%2Cexamples-of-common-violations
https://support.google.com/admob/answer/6223431

They send to you any screenshots? 

I think it must be some misunderstanding with Apple when they say "when tapped, take the user to the web page of the App Store" because if that is the case, no games aimed at kids should be published in the App Store.

Try publish again, if they reject you would be good to talk to them for help.

https://developer.apple.com/contact/
https://developer.apple.com/support/app-store-connect/

**Comment by shafnaz** [comment]
I remember i set it to PG, not G. Would that solve it? what about the parental gate? does that imply  that a window message should popup first before taking the user to the advertisement?

**Comment by shafnaz** [comment]
They  are talking about this right?
![image](https://user-images.githubusercontent.com/37254287/140233379-f7dcd851-3fb0-4cd3-a369-011429d6ac04.png)
Got this image from:
[](https://sa-mobile-sdk-ios.superawesome.tv/docs/parental-gate)

**Comment by gumaciel** [comment]
I didn't know about Parental Gate, I've been researching and realized that AdMob doesn't support it for iOS (or Android), because as soon as the user clicks on the banner or some advertisement like that the user is always taken to some internet link, there are some related questions on the internet about Parental Gate with AdMob for iOS, but none of them say how to actually solve the problem.

https://groups.google.com/g/google-admob-ads-sdk/c/8HmWaAIlzUY/m/Gs3ktpc6BwAJ
https://stackoverflow.com/a/42536426


This answer can be intersting: `You could implement your parental control at the beginning of your app. If it pass, show ads, if not don't show ads.`

**Comment by shafnaz** [comment]
We can close this issue, as there is no parental gate support from admob

**Comment by kyoz** [comment]
I'm closing this cause everything seem clear now. If there is any issues relate please open new issues.
